### ISSUE TITLE
any plans to support Firefox 5+?

### ISSUE THREAD

**Issue by triptych** [boblemarin/Sprite3D.js#1]
Not sure if they support everything yet, but perhaps have something more than just a completely broken view?

http://hacks.mozilla.org/2011/06/rofox-a-css3-animations-demo/

**Comment by boblemarin** [comment]
thanks for watching.
but what they are bringing in Firefox is CSS keyframed animation, using 2D transforms.

Sprite3D uses the 3D transforms, with the advantage of triggering the hardware acceleration when possible.

I don't know if 2D transforms have the same chance, but it could be easy to port the code to a 2D version that could be more compatible.

**Comment by boblemarin** [comment]
FYI, I have been trying Sprite3D with Firefox 10 nightly, and some demos are working with great performance (i.e. the image gallery). Others are broken.

On my side, vendor prefixes are implemented, so I'm just waiting for the browsers to evolve.

**Comment by boblemarin** [comment]
Firefox is supported starting at version 10.
