### ISSUE TITLE
Cyclinder Shape

### ISSUE THREAD

**Issue by karneaud** [boblemarin/Sprite3D.js#10]
Is there any way to create a more cylindrical shape? I'm trying to make mimic a almost 3D bottle using image sprites.

**Comment by boblemarin** [comment]
Well, you can't create a real cylinder, only planes. But as you can draw a circle using a succession of shot strait lines, you can build a cylinder with short plane faces. The more faces you use, the more curved your shape appears.

So there is not really a perfect solution, only approximations.

Maybe you should check what you can do with WebGL if you want more curves.
