### ISSUE TITLE
Sprite3D.js does not work in Safari 6 (Mountain Lion)

### ISSUE THREAD

**Issue by ohmybrain** [boblemarin/Sprite3D.js#5]
Hello,
First this is a great script and I have been building some stuff on it. Today with OS X Mountain Lion we got Safari 6 and everything I built using this lovely script broke. White screen of death. However if you mouse drag for example where you think the box example might be and lean if forward the front of the box will show up for a second. This shows the objects are in place but are being clipped by the background or maybe a z-index issue.

Not sure if this project is still being maintained. If so I would be more then glad to send some screenshots or a screen cast.

super thanks in advance

Brian Williford.

**Comment by boblemarin** [comment]
Hi Brian,

I've been testing the library under Safari 6 (Lion) without any problem so far, so it sounds like a surprise. Any error showing in the console ? Does the inspector behave normally ?
Please send me a link to your stuff, I'll test it on my machine and we'll try to find where the problem comes from.

Are you using the v2 ? (both perform equally well here on Safari 6 / Lion).

**Comment by ohmybrain** [comment]
Bob,

Here is a sample URL:
http://mo-g.com

Sounds like it might be a Safari Six Mountain Lion combo issue if you are using Lion. I upgraded both at the same time.
The link above was built on your box example version 1. I only discovered version 2 yesterday. I am in the process of swapping out the box assets but the few parts from your example still remains.

I also added jQuery and isotope.min.js. However I tested your original box example and v2 on my Mac Air and get the same issue. I get no script errors which may support something in Mountain Lion being the cause.

Thanks again for your time.

Brian

**Comment by ohmybrain** [comment]
Forgot to mention it this example works fine with FireFox 14

**Comment by boblemarin** [comment]
You example works fine on all my browsers under Lion (Chrome 20, Firefox 14, Safari 6). I noticed some strange behavior regarding mouse events in Safari, but when I resized my window and opened the inspector, it worked fine again.

As I don't have Mountain Lion installed here, there's not much I can do. Can you check the inspector to see if there are CSS rules that are disabled ? maybe there's some new un-prefixed css properties that make my browser detection fail.

**Comment by ohmybrain** [comment]
Nothing really of value on the css inspector. Thanks for looking. I will assume Apple will update the browser in a week or so from bug reports. Issue may resolve itself that way.

Thanks!

**Comment by boblemarin** [comment]
ok, let me know if there's any evolution.

I just upgraded to Lion a few weeks ago, so I'm not that keen on buying Mountain Lion right now...

emeric

**Comment by boblemarin** [comment]
Ok, I found what's causing the bug. Looks like the root container (stage) must NOT have its transform-style property set to "preserve-3d".
I added the fix in both v1 and v2, so be sure to download the latest builds.

**Comment by ohmybrain** [comment]
Bob, 
I will download the latest build in a day or two and give it a shot. 

You are the man!

**Comment by ohmybrain** [comment]
Downloaded latest version and the 3D Scene now shows up in the Safari 6 on Mountain Lion. However the movement has issues. In testing with the Box example I can spin the box maybe 20 04 30 pixels and the mouse lets go of the object. On the second and third try the box just moves a little in a random direction.

I would gladly purchase Mountain Lion for you if this helps or offer to pay you for your time. I understand how these single or low user use cases can burden ones time. :)

**Comment by boblemarin** [comment]
I had the opportunity to upgrade to ML, so it's okay.

When you're having the mouse problem, try to open the inspector window. When I do, the mouse acts normally. Unti now, I can't really tell if it's related to Sprite3D.
